### ISSUE TITLE
pm2 doesn't start correctly after a restart

### ISSUE THREAD

**Issue by petre2dor** [petre2dor/piGarden#11]
I think I messed up `pm2 startup` when I updated nodejs install without nvm. See update-5.sh

**Comment by rcursaru** [comment]
pm2 tries to start the processes before vagrant had the chance to mount the shared folder
https://stackoverflow.com/questions/35697638/pm2-errored-when-vagrant-is-reloaded-or-restarted

pushed c3ee0aa to fix it

**Comment by petre2dor** [comment]
this is working properly now
