### ISSUE TITLE
PI_GARDEN_ENV is not defined by default

### ISSUE THREAD

**Issue by rcursaru** [petre2dor/piGarden#36]
1|AC       | TypeError: Cannot read property 'sufix' of undefined
1|AC       |     at Object.<anonymous> (/piGarden/devices/controller/temperature/Temperature.js:8:77)
1|AC       |     at Module._compile (module.js:570:32)
1|AC       |     at Object.Module._extensions..js (module.js:579:10)
1|AC       |     at Module.load (module.js:487:32)
1|AC       |     at tryModuleLoad (module.js:446:12)
1|AC       |     at Function.Module._load (module.js:438:3)
1|AC       |     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
1|AC       |     at Module.require (module.js:497:17)
1|AC       |     at require (internal/module.js:20:19)
1|AC       |     at Object.<anonymous> (/piGarden/devices/Routes.js:3:19)

**Comment by rcursaru** [comment]
@petre2dor should we put a conditional testing for PI_GARDEN_ENV (and assume an answer if variable is not set) or should we set PI_GARDEN_ENV at each deployment?

**Comment by rcursaru** [comment]
for now I added a default setting to DEV in app.json

**Comment by petre2dor** [comment]
I would go with having it set it up all the time
